/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shah' at '10/21/15 6:16 AM' with Gradle 2.5
 *
 * @author shah, @date 10/21/15 6:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
